# vi: expandtab shiftwidth=2 softtabstop=2

# First scenario is configured as warmup
- termination: http
  connections: 200
  samples: 3
  duration: 3m
  path: /1024.html
  concurrency: 5
  tool: wrk
  serverReplicas: 25
  delay: 10s
  requestTimeout: 10s
  warmup: true

# Throughput tests
- termination: http
  connections: 200
  samples: 2
  duration: 5m
  path: /1024.html
  concurrency: 5
  tool: wrk
  serverReplicas: 25
  requestTimeout: 10s
  delay: 10s

- termination: edge
  connections: 200
  samples: 2
  duration: 5m
  path: /1024.html
  concurrency: 5
  tool: wrk
  serverReplicas: 25
  requestTimeout: 10s
  delay: 10s

# Latency tests
- termination: http
  connections: 200
  samples: 2
  duration: 3m
  path: /1024.html
  concurrency: 1
  tool: hloader
  serverReplicas: 25
  requestTimeout: 10s
  delay: 10s
  requestRate: 5000
  http2: true

- termination: edge
  connections: 200
  samples: 2
  duration: 3m
  path: /1024.html
  concurrency: 1
  tool: hloader
  serverReplicas: 25
  requestTimeout: 10s
  delay: 10s
  requestRate: 5000
  http2: true